version: "3"
services:

  laravel:
    build: ./
    container_name: laravel
    entrypoint: dockerize -template ./docker/app/env:.env -wait tcp://db:3306 -timeout 40s ./entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes: 
      - .:/var/www
    networks: 
      - laravel-network
    depends_on:
      - db
      - redis

  nginx:
    build: ./docker/nginx
    restart: always
    entrypoint: dockerize -template ./var/www/docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf -wait tcp://laravel:9000  -timeout 40s nginx -g "daemon off;"
    environment:
      - REDIRECT_HOST=laravel
      - NGINX_PORT=9000
    tty: true
    ports:
      - "8000:80"
    networks: 
      - laravel-network
    volumes:
      - .:/var/www
    depends_on:
      - laravel
      
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
    - ./mysql/data:/var/lib/mysql
    
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root 
    networks: 
      - laravel-network

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

